name: Build the package

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}  
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build the package
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    - run: npm run-script build:lib
    - name: Publish package 
      working-directory: dist/protools/angular
      run: npm publish
